# Generated by Django 4.2.15 on 2024-08-23 08:13

from django.db import migrations, models
import restapi.utils


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_url',
            field=models.IntegerField(default=restapi.utils.random_img_int),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='view_count',
            field=models.IntegerField(default=restapi.utils.random_view_int),
        ),
    ]
